### ISSUE TITLE
Implement Header component

### ISSUE THREAD

**Issue by HNY-Badger** [HNY-Badger/ecommerce-app#5]
**Requirements**: User's authentication state is implemented

Create Header component according to Figma design. Create burger menu for mobile devices. In case user is unauthorized, this component should include Login and Register buttons that lead to related pages, if user is authorized, Logout button should appear instead. Clicking Logout button also should redirect user to the Login page.

**Note**: links to WIP pages should lead to 404.

- Navigation to login and registration pages for unauthorized users [RSS-ECOMM-2_21](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint2/RSS-ECOMM-2_21.md)
- Ability to access the main page for all users [RSS-ECOMM-22](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint2/RSS-ECOMM-2_22.md)
- Logout functionality for authorized users [RSS-ECOMM-2_23](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint2/RSS-ECOMM-2_23.md)

**Comment by Lneer** [comment]
Mistake
